FROM letunovms/smartoffice:base

ARG node=https://nodejs.org/dist/v6.10.0/node-v6.10.0-linux-armv7l.tar.xz
RUN wget -qO- $node | tar xvJ --strip-components=1 -C usr/local && \
    npm config set unsafe-perm true -g --unsafe-perm