FROM letunovms/smartoffice:base

ENV JAVAHOME=/usr/lib/jvm/java-8-openjdk-armhf JENKINS_HOME=/var/jenkins JENKINS_WAR=/var/jenkins.war
COPY jenkins.sh /tmp
RUN chmod +x /tmp/jenkins.sh && sync && /tmp/jenkins.sh && rm /tmp/jenkins.sh

VOLUME /var/jenkins
EXPOSE 8080
ENTRYPOINT /usr/bin/java -jar $JENKINS_WAR