FROM letunovms/smartoffice:base-node

RUN apt-get install -y git python build-essential && \
    apt-get install -y cron && \
    mkdir -p /var/cron/cron.d && \
    mv /etc/cron.d /var/cron/cron.d && \
    ln -s /var/cron/cron.d /etc/cron.d

VOLUME /var/cron
CMD ["cron", "-f"]