FROM letunovms/smartoffice:base

RUN apt-get install -y cron && \
    mkdir -p /var/cron/cron.d && \
    mv /etc/cron.d /var/cron/cron.d && \
    ln -s /var/cron/cron.d /etc/cron.d

VOLUME /var/cron
CMD ["cron", "-f"]

ARG node=https://nodejs.org/dist/v6.10.0/node-v6.10.0-linux-armv7l.tar.xz
RUN apt-get install -y git python build-essential && \
    wget -qO- $node | tar xvJ --strip-components=1 -C usr/local && \
    npm config set unsafe-perm true -g --unsafe-perm && \
    npm install webpack node-gyp -g